name: build
on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - run: apt update
      - name: install aux deps
        run: apt -y --no-install-recommends install git ca-certificates curl gnupg
      - name: clone repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: install build-deps
        run: apt -y --no-install-recommends build-dep .
      - name: build
        run: dpkg-buildpackage -us -uc -b -j$(nproc)

      - uses: yeti-switch/upload-debian-pkg-action@v1
        with:
          pkgs: '../*.deb'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          aws_bucket: ${{ secrets.DEB_AWS_BUCKET }}
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
          AWS_ACCESS_KEY_ID: ${{secrets.DEB_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DEB_AWS_SECRET_ACCESS_KEY}}
          AWS_ENDPOINT_URL: ${{secrets.DEB_AWS_ENDPOINT}}
        if: startsWith(github.ref, 'refs/tags/v')
