name: build
on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:${{ matrix.distribution }}
    strategy:
      matrix:
       distribution: [bookworm, trixie]
    steps:
      - run: apt update
      - name: install aux deps
        run: apt -y --no-install-recommends install git ca-certificates curl gnupg
      - name: clone repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: install build-deps
        run: apt -y --no-install-recommends build-dep .
      - name: build
        run: dpkg-buildpackage -us -uc -b -j$(nproc)

      - uses: yeti-switch/upload-debian-pkg-action@v2
        with:
          pkgs: '../*.deb'
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          s3_access_key_id: ${{ secrets.DEB_AWS_ACCESS_KEY_ID }}
          s3_secret_access_key: ${{ secrets.DEB_AWS_SECRET_ACCESS_KEY }}
          s3_endpoint_url: ${{ secrets.DEB_AWS_ENDPOINT }}
          s3_codename: ${{ matrix.distribution }}
          s3_prefix: '1.14'
        if: startsWith(github.ref, 'refs/tags/v')

